### ISSUE TITLE
ValueError: No data provided for "input_1". Need data for each key in: ['input_1']

### ISSUE THREAD

**Issue by yokoyoko123** [KinarR/age-gender-estimator-keras#1]
Trying to train this model with imdb datasets(README.md) on google colab, this error(title) occured.
How to resolve?

**Error details below.**
Using TensorFlow backend.
DEBUG:root:Loading data...
Samples: Training - 74730, Validation - 18683
DEBUG:root:image_dim_ordering = 'tf'
DEBUG:root:Creating model...
DEBUG:root:Model summary...
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
mobilenet_1.00_224 (Model)      (None, 7, 7, 1024)   3228864     input_1[0][0]                    
__________________________________________________________________________________________________
global_average_pooling2d_1 (Glo (None, 1024)         0           mobilenet_1.00_224[1][0]         
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 1024)         0           global_average_pooling2d_1[0][0] 
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1024)         1049600     dropout_1[0][0]                  
__________________________________________________________________________________________________
gender (Dense)                  (None, 2)            2050        dense_1[0][0]                    
__________________________________________________________________________________________________
age (Dense)                     (None, 21)           21525       dense_1[0][0]                    
==================================================================================================
Total params: 4,302,039
Trainable params: 4,280,151
Non-trainable params: 21,888
__________________________________________________________________________________________________
DEBUG:root:Saving model...
MobileNet - 32 OIHKKBFZAH
/usr/local/lib/python3.6/dist-packages/keras/callbacks.py:928: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` insted.
  warnings.warn('`epsilon` argument is deprecated and '
DEBUG:root:Running training...
Epoch 1/70
/usr/local/lib/python3.6/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/local/lib/python3.6/dist-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 63, in _standardize_input_data
    data = [data[x].values if data[x].__class__.__name__ == 'DataFrame' else data[x] for x in names]
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 63, in <listcomp>
    data = [data[x].values if data[x].__class__.__name__ == 'DataFrame' else data[x] for x in names]
KeyError: 'input_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main()
  File "train.py", line 131, in main
    validation_steps=int(len(val_keys) / batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 2230, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1877, in train_on_batch
    class_weight=class_weight)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 67, in _standardize_input_data
    'for each key in: ' + str(names))
ValueError: No data provided for "input_1". Need data for each key in: ['input_1']

**Comment by kinaryml** [comment]
To resolve this rename the input layer name in data_generaror.py to 'input_1'

def _wrap_in_dictionary(self, image_array, gender, age_quantized):
        return [
            {'input_1': image_array},
            {'gender': gender, 'age': age_quantized}
        ]

**Comment by KinarR** [comment]
To resolve this rename the input layer to 'input_1' as follows 
def _wrap_in_dictionary(self, image_array, gender, age_quantized):
        return [
            {'input_1': image_array},
            {'gender': gender, 'age': age_quantized}
        ]

You could even set the name of the input explicitly models/mobile_net.py
inputs = Input(shape=self._input_shape, name='the_input')

**Comment by KinarR** [comment]
To resolve this, rename the input layer in data_generator.py to 'input_1' as follows 
```
def _wrap_in_dictionary(self, image_array, gender, age_quantized):
        return [
            {'input_1': image_array},
            {'gender': gender, 'age': age_quantized}
        ]
```

You could even set the name of the input explicitly in models/mobile_net.py
```
inputs = Input(shape=self._input_shape, name='the_input')
```

**Comment by yokoyoko123** [comment]
Thank you for reply!
The program is working properly so far.

And There's something I'd like to ask.
I want you to make Instructions on how to use "predict.py".
I would like to check results with pictures taken by myself!

**Comment by spartian** [comment]
Hello, I am facing a similar issue . Can you help me with this?
