### ISSUE TITLE
How to View and and edit *.MAT file?

### ISSUE THREAD

**Issue by hbsuhas** [KinarR/age-gender-estimator-keras#4]
Hi KinarR

I would like to read and edit the .MAT file.
Can you please help me with the software/tool? 

thank you
Suhas hB

**Comment by KinarR** [comment]
I believe you could open it in MS Access

**Comment by hbsuhas** [comment]
It's not possible to open in mS access.

**Comment by KinarR** [comment]
Uh, then you may load the MAT in python and convert it to a CSV which is easily readable by most spreadsheet applications.
